### ISSUE TITLE
1.10.3 breaks "sls invoke local"

### ISSUE THREAD

**Issue by taschmidt** [floydspace/serverless-esbuild#120]
Upgraded to 1.10.3 to fix #117 which now works with serverless >= 2.36.0. However, it appears to have broken `invoke local`. I get a "cannot find module" error and it appears to be looking in `src/...` rather than `.esbuild/.build/src/...`:

```
Error: Cannot find module '/Users/schmidtt/w/video-tracking/src/list'
Require stack:
- /Users/schmidtt/w/video-tracking/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js
- /Users/schmidtt/w/video-tracking/node_modules/serverless/lib/plugins/index.js
- /Users/schmidtt/w/video-tracking/node_modules/serverless/lib/classes/PluginManager.js
- /Users/schmidtt/w/video-tracking/node_modules/serverless/lib/Serverless.js
- /Users/schmidtt/w/video-tracking/node_modules/serverless/scripts/serverless.js
- /Users/schmidtt/w/video-tracking/node_modules/serverless/bin/serverless.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at AwsInvokeLocal.invokeLocalNodeJs (/Users/schmidtt/w/video-tracking/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:743:33)
    at AwsInvokeLocal.invokeLocal (/Users/schmidtt/w/video-tracking/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:222:19)
    at Object.invoke:local:invoke [as hook] (/Users/schmidtt/w/video-tracking/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:49:47)
    at PluginManager.invoke (/Users/schmidtt/w/video-tracking/node_modules/serverless/lib/classes/PluginManager.js:551:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by taschmidt** [comment]
This could be an issue with core serverless >= 2.36.0. I encountered the same error in a different project that doesn't even use esbuild (webpack).

**Comment by floydspace** [comment]
hi @taschmidt, thank you for the issue, we've merged the fix. If you have a chance could you please check if it works for you?

**Comment by taschmidt** [comment]
Yep, looks like it's fixed. Thanks!!
